### ISSUE TITLE
是否有对wx:else做处理

### ISSUE THREAD

**Issue by a145789** [ctripcorp/wean#22]
wx:else 会 编译为 directs.$else(() => ,
看了下好像是通过 const [name, value] = node.directives[i] 获取条件， else 得到的是 [ 'wx:else', '' ]，没有和 if 做联动么？

**Comment by yisar** [comment]
是的，暂时没有做联动，还在思考咋搞

**Comment by yisar** [comment]
这个感觉必须在编译期间做，而且三个代码块要同时编译成一个函数，周六日我搞搞看

**Comment by a145789** [comment]
我也想了一下这个东西，觉得最好的方式还是编译成vue的那种三元运算符形式

**Comment by yisar** [comment]
> 我也想了一下这个东西，觉得最好的方式还是编译成vue的那种三元运算符形式

vue 编译成哪样了

**Comment by a145789** [comment]
> > 我也想了一下这个东西，觉得最好的方式还是编译成vue的那种三元运算符形式
> 
> vue 编译成哪样了

e.viewShow ? a('yl-img-upload', { ref: 'imgUploadFeedback', attrs: { 'is-details': !0, limit: 10 } }) : e._e()
vue2

**Comment by yisar** [comment]
https://github.com/ctripcorp/wean/pull/38
