### ISSUE TITLE
和uniapp 比优势是啥？

### ISSUE THREAD

**Issue by muwoo** [ctripcorp/wean#59]
uniapp 比较稳定，也比较好用，不太明白和uniapp 竞争的话，优势在哪

**Comment by yisar** [comment]
uniapp 是 vue 标准，不是微信标准……而且它主要是做跨端的

wean 主要是将标准的微信小程序转成 web，然后跑到 webview 中，类似于小程序引擎，只是没有用双线程而已

另一方面，虽然 uniapp 比较稳定，但架构上还是 wean 更靠谱，只是我现在还在搞，距离稳定还差得远

**Comment by yisar** [comment]
另外，wean 之所以自己实现整个打包过程，是为了缩短开发链路
其他工具都是借助 webpack 的，链路是很长的，开发调试测试都很痛苦的

**Comment by yisar** [comment]
过去，wean 自己实现了打包过程，这是几乎所有 bug 的来源😓 为了减少碎片化，我准备使用重构了
